services:
  api:
    build:
      context: .
      dockerfile: infra/Dockerfile.api
    container_name: ai_support_api
    env_file:
      - .env
    environment:
      # 并发阈值：为便于本地复现 429，显式设为 1。生产可删除或调整为更高数值。
      - DOWNLOAD_MAX_CONCURRENCY=1
      - EXPORT_MAX_CONCURRENCY=1
      # 可选覆盖：日志级别与 CORS 来源（也可放入 .env）
      # - LOG_LEVEL=INFO
      # - CORS_ORIGINS=*
    ports:
      - "${API_PORT:-8000}:8000"
    command: ["uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./src:/app/src
    depends_on:
      - db
      - redis
      - qdrant
      - ollama

  db:
    image: postgres:16
    container_name: ai_support_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ai_support_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: ai_support_qdrant
    ports:
      - "${QDRANT_PORT:-6333}:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    container_name: ai_support_ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama_data:/root/.ollama

  prometheus:
    image: prom/prometheus:latest
    container_name: ai_support_prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./configs/rules:/etc/prometheus/rules:ro
      - prometheus_data:/prometheus
    depends_on:
      - api

  alertmanager:
    image: prom/alertmanager:latest
    container_name: ai_support_alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./configs/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: ai_support_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/provisioning/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./configs/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    depends_on:
      - prometheus

volumes:
  db_data:
  redis_data:
  qdrant_data:
  ollama_data:
  prometheus_data:
  alertmanager_data:
  grafana_data:
