name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

      - name: Smoke ask (plain + RAG)
        run: |
          bash scripts/smoke_ask.sh

      - name: RAG evaluation gate
        env:
          GATE_MIN_TOTAL: "5"
          GATE_REQUIRE_MIN_TOTAL: "0"
          RAG_EVAL_QUERIES: demo.jsonl
          RAG_TOP_K: "5"
        run: |
          bash scripts/rag_eval_gate.sh
