name: Update Progress README

on:
  workflow_run:
    workflows: ["Progress Report"]
    types: [completed]

permissions:
  contents: write

jobs:
  update-readme:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update README with latest Progress Report artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          README_PATH: README.md
          WORKFLOW_FILE: progress.yml
        run: |
          python -m pip install --upgrade pip
          python scripts/ci/update_progress_readme.py

      - name: Commit changes if any
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs(readme): auto-update Progress Report links [skip ci]"
          git push
